config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :boards do
    resources :columns do
      resources :stories
    end
  end

  get '/users/:id', to: 'users#show'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "boards#index"
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/column.rb
class Column < ApplicationRecord
  belongs_to :board
  has_many :stories, -> { order(position: :asc) }, dependent: :destroy
end

app/controllers/columns_controller.rb
class ColumnsController < ApplicationController
  before_action :get_board
  before_action :set_column, only: %i[ show edit update destroy ]

  # GET /columns or /columns.json
  def index
    @columns = @board.columns
  end

  # GET /columns/1 or /columns/1.json
  def show
  end

  # GET /columns/new
  def new
    @column = @board.columns.build
  end

  # GET /columns/1/edit
  def edit
  end

  # POST /columns or /columns.json
  def create
    @board = Board.find(params[:board_id])
    @column = @board.columns.build(column_params)

    respond_to do |format|
      if @column.save
        format.json { render :show, status: :created, location: [@board, @column] }
      else
        format.json { render json: @column.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /columns/1 or /columns/1.json
  def update
    @board = Board.find(params[:board_id])
    respond_to do |format|
      if @column.update(column_params)
        format.json { render :show, status: :ok, location: @column }
      else
        format.json { render json: @column.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /columns/1 or /columns/1.json
  def destroy
    @column.destroy

    respond_to do |format|
      format.json { head :no_content }
    end
  end
  
  private
  
    def get_board
      @board = Board.find(params[:board_id])
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_column
      @column = @board.columns.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def column_params
      params.require(:column).permit(:name, :board_id, :position)
    end
end

app/helpers/columns_helper.rb
module ColumnsHelper
end

app/views/columns/_column.html.erb
<div id="<%= dom_id column %>">
  <p>
    <strong>Name:</strong>
    <%= column.name %>
  </p>

  <p>
    <strong>Board:</strong>
    <%= column.board_id %>
  </p>

  <p>
    <strong>Position:</strong>
    <%= column.position %>
  </p>

</div>

app/views/columns/_form.html.erb
<%= form_with(model: [:board, @column], url: board_columns_path(@board, @column)) do |form| %>
  <% if column.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(column.errors.count, "error") %> prohibited this column from being saved:</h2>

      <ul>
        <% column.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :board_id, style: "display: block" %>
    <%= form.text_field :board_id %>
  </div>

  <div>
    <%= form.label :position, style: "display: block" %>
    <%= form.number_field :position %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/columns/edit.html.erb
<h1>Editing column</h1>

<%= render "form", column: @column %>

<br>

<div>
  <%= link_to "Show Column", board_column_path(@board, @column) %> |
  <%= link_to "Back to columns", board_columns_path(@board) %>
</div>

app/views/columns/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Columns</h1>

<div id="columns">
  <% @columns.each do |column| %>
    <%= render column %>
    <p>
      <%= link_to "Show Column", board_column_path(@board, column) %>
    </p>
  <% end %>
</div>

<%= link_to "New column", new_board_column_path %>

app/views/columns/new.html.erb
<h1>New column</h1>

<%= render "form", column: @column %>

<br>

<div>
  <%= link_to "Back to columns", board_columns_path %>
</div>

app/views/columns/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @column %>

<div>
  <%= link_to "Edit this column", edit_board_column_path(@board) %> |
  <%= link_to "Back to columns", board_columns_path %>

  <%= button_to "Destroy this column", @board_column, method: :delete %>
</div>