config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :boards do
    resources :columns do
      resources :stories
    end
  end

  get '/users/:id', to: 'users#show'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "boards#index"
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :column

  # default_scope { where(:status => 1 )}

  # scope :in_progress, -> { where(status: "In progress")}
  scope :solved, -> { where(status: "Solved") }
  scope :old, -> { where(Story.arel_table(:created_at).lt(Date.today-60))}
  scope :overdue, -> { where (Story.arel_table(:due_date).gt(Date.today))}

  scope :filter_by_status_and_date, -> (statuses, dates) {
    where(status: statuses).where(due_date: dates)
  }
end

app/controllers/stories_controller.rb
require_relative '../services/stories_retriever.rb'

class StoriesController < ApplicationController
  before_action :get_board_and_column
  before_action :set_story, only: %i[ show edit update destroy ]
  # before_action :set_due_date
  # GET /stories or /stories.json
  def index
    @column = Column.find(params[:column_id])
    

    status = []
    due_date = []
    column = :title
    type = :asc

    if params[:status] || params[:due_date] || params[:column] || params[:type]
      if params[:status].present?
        status = params[:status].split(',')
      end
      if params[:due_date].present?
        due_date = params[:due_date].split(',')
      end
      if params[:column].present?
        column = params[:column]
      end
      if params[:type].present?
        type = params[:type]
      end

      @stories = StoriesRetriever.new.filter_order(
          params[:column_id],
          statuses: status,
          dates: due_date,
          order_column: column,
          order_type: type
          )
    else
      @stories = @column.stories.all
    end
    # @stories = StoriesRetriever.new.filter_by_status_and_date(
    #   params[:column_id],
    #   statuses: 1,
    #   dates: (Date.today - 30)..(Date.today + 30)
    # )

    # @stories = StoriesRetriever.new.order_by(
    #   params[:column_id],
    #   order_column: :title,
    #   order_type: :desc
    # )

    render json: @stories, status: :ok

    # @stories = Story.reorder(created_at: :asc)
  end

  def show
    @story = @column.stories.find_by(id: params[:id])
    if @story
      render json: @story
    else
      render json: { error: "Story not found" }, status: :not_found
    end

  end

  # GET /stories/new
  def new
    @story = @column.stories.build
  end

  # GET /stories/1/edit
  def edit
  end

  # POST /stories or /stories.json
  def create
    @column = Column.find(params[:column_id])
    @story = @column.stories.build(story_params)

    respond_to do |format|
      if @story.save
        format.json { render :show, status: :created, location: [@board, @column, @story] }
      else
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1 or /stories/1.json
  def update
    @column = Column.find(params[:column_id])
    respond_to do |format|
      if @story.update(story_params)
        format.json { render :show, status: :ok, location: [@board, @column, @story] }
      else
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1 or /stories/1.json
  def destroy
    @column = Column.find(params[:column_id])
    @story.destroy

    respond_to do |format|
      format.json { head :no_content }
    end
  end

  # def set_due_date
  #   self.due_date =  Time.now + 60.days
  # end 

  private

    def get_board_and_column
      @board = Board.find(params[:board_id])
      @column = @board.columns.find(params[:column_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = @column.stories.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def story_params
      params.require(:story).permit(:title, :position, :description, :status, :due_date)
    end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.erb
<%= form_with(model: [:board, :column, @story], url: board_column_story_path(@board, @column, @story)) do |form| %>
  <% if story.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
        <% story.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :column_id, style: "display: block" %>
    <%= form.text_field :column_id %>
  </div>

  <div>
    <%= form.label :position, style: "display: block" %>
    <%= form.number_field :position %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/stories/_story.html.erb
<div id="<%= dom_id story %>">
  <p>
    <strong>Title:</strong>
    <%= story.title %>
  </p>

  <p>
    <strong>Column:</strong>
    <%= story.column_id %>
  </p>

  <p>
    <strong>Position:</strong>
    <%= story.position %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= story.description %>
  </p>

</div>

app/views/stories/edit.html.erb
<h1>Editing story</h1>

<%= render "form", story: @story %>

<br>

<div>
  <%= link_to "Show this story", board_column_story_path(@board, @column, @story) %> |
  <%= link_to "Back to stories", stories_path %>
</div>

app/views/stories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Stories</h1>

<div id="stories">
  <% @stories.each do |story| %>
    <%= render story %>
    <p>
      <%= link_to "Show this story", [@board, @column, story] %>
    </p>
  <% end %>
</div>

<%= link_to "New story", new_board_column_story_path(@column) %>
<br>
<%= link_to "Back to Columns", board_columns_path(@column.board_id) %>

app/views/stories/new.html.erb
<h1>New story</h1>

<%= render "form", story: @story %>

<br>

<div>
  <%= link_to "Back to stories", stories_path %>
</div>

app/views/stories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @story %>

<div>
  <%= link_to "Edit this story", edit_board_column_story_path(@story) %> |
  <%= link_to "Back to stories", board_column_stories_path %>

  <%= button_to "Destroy this story", @board_column_story, method: :delete %>
</div>