config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :boards do
    resources :columns do
      resources :stories
    end
  end

  get '/users/:id', to: 'users#show'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "boards#index"
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/board.rb
class Board < ApplicationRecord
    acts_as_paranoid
    has_paper_trail
    has_many :columns, -> { order(position: :asc) }, dependent: :destroy
    belongs_to :user
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :set_paper_trail_whodunnit
  # before_action :check_permission_level, only: [:index]
  # GET /boards or /boards.json
  def index
    # @boards = Board.all
    @boards = current_user.boards
    render json: @boards, status: :ok
  end

  # GET /boards/1 or /boards/1.json
  def show
    @board = Board.find(params[:id])
    authorize @board
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards or /boards.json
  def create
    @board = current_user.boards.build(board_params)
    authorize @board

    respond_to do |format|
      if @board.save
        format.json { render :show, status: :created, location: @board }
      else
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1 or /boards/1.json
  def update
    @board = Board.find(params[:id])
    authorize @board

    respond_to do |format|
      if @board.update(board_params)
        format.json { render :show, status: :ok, board: @board }
      else
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1 or /boards/1.json
  def destroy
    @board.destroy
    authorize @board
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def board_params
      params.require(:board).permit(:title)
    end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_board.html.erb
<div id="<%= dom_id board %>">
  <p>
    <strong>Title:</strong>
    <%= board.title %>
  </p>

</div>

app/views/boards/_form.html.erb
<%= form_with(model: board) do |form| %>
  <% if board.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
        <% board.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<h1>Editing board</h1>

<%= render "form", board: @board %>

<br>

<div>
  <%= link_to "Show this board", @board %> |
  <%= link_to "Back to boards", boards_path %>
</div>

app/views/boards/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Boards</h1>

<div id="boards">
  <% @boards.each do |board| %>
    <%= render board %>
    <p>
      <%= link_to "Show this board", board %>
    </p>
  <% end %>
</div>

<%= link_to "New board", new_board_path %>

app/views/boards/new.html.erb
<h1>New board</h1>

<%= render "form", board: @board %>

<br>

<div>
  <%= link_to "Back to boards", boards_path %>
</div>

app/views/boards/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @board %>

<div>
  <%= link_to "Edit this board", edit_board_path(@board) %> |
  <%= link_to "Back to boards", boards_path %>

  <%= button_to "Destroy this board", @board, method: :delete %>
</div>